version: '3.9'

services:
  mongodb:
    image: mongo
    env_file:
      - .env
    ports:
      - "27018:27017"
    volumes:
      - pidb:/data/db

  pingo:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3241:3241"
    depends_on:
      - mongodb
    volumes:
      - ./app/:/src/app
      - ./static/:/src/static
      - ./templates/:/src/templates

volumes:
  pidb:
