version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - pidb:/data/db

  pingo:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3241:3241"
    depends_on:
      - mongodb
    working_dir: /src/app
    volumes:
      - ./app/:/src/app

volumes:
  pidb:
